name: Macos release

on:
  workflow_dispatch: ~

jobs:
  build-platforms:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Linux specific deps
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          make venv || echo "it's fine"
          source .venv/bin/activate
          pip install -f "https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.0-cp310-cp310-linux_x86_64.whl" wxPython || echo "it's fine"

      - name: Package application
        run: |
          pip3 install pyinstaller
          make release

      - name: Prepare files
        run: |
          mkdir release
          cp resources/* release
          cp dist/ws_osd_gen* release
          tar -a -c -f "release-${{ github.ref_name }}-${{ matrix.os }}.zip" release

      - uses: actions/upload-artifact@v3
        with:
          name: release-${{ github.ref_name }}-${{ matrix.os }}
          path: release-${{ github.ref_name }}-${{ matrix.os }}.zip
  build-macos:
    runs-on: macos-12

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -U py2app

    - name: Package application
      run: |
        make venv
        source .venv/bin/activate
        py2applet --make-setup osd_gui.py
        python3 setup.py py2app


    - name: Prepare files
      run: |
        mkdir release
        cp resources/* release
        cp -a dist/osd_gui.app release
        tar -a -c -f "release-${{ github.ref_name }}-macos-12.zip" release


    - uses: actions/upload-artifact@v3
      with:
        name: release-${{ github.ref_name }}-macos-12
        path: release-${{ github.ref_name }}-macos-12.zip