name: Package and Release Python Application

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Package application
      run: |
        make release

    - name: Prepare files
      run: |
        mkdir release
        cp resources/* release
        cp dist/ws_osd_gen.exe release
        tar -a -c -f "release-${{ github.ref_name }}-windows.zip" release


    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        prerelease: false
        draft: true
        fail_on_unmatched_files: true
        generate_release_notes: true
        files: release-${{ github.ref_name }}-windows.zip
        append_body: true
        body: |
          This is a latest release from master branch.
          ---
          ## Coffee needed
          If you like tool, you can buy me a coffee so keep working more overnights :) 

          <a href="https://www.buymeacoffee.com/kirek" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png" alt="Buy Me A Coffee" style="height: 30px !important;width: 108 !important;" ></a>
