name: Package and Release Python Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Package application
      run: |
        make release

    - name: Prepare files
      run: |
        mkdir release
        cp resources/* release
        cp dist/ws_osd_gen.exe release
        tar -a -c -f "pre-release-${{ github.sha }}-windows.zip" release


    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: master-${{ github.sha }}
        name: Pre-release ${{ github.sha }}
        prerelease: true
        fail_on_unmatched_files: true
        generate_release_notes: true
        files: pre-release-${{ github.sha }}-windows.zip
        append_body: "This is latest build from master branch"
